sudo: required
language: python
python:
    - "3.4"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - psql -c 'CREATE DATABASE "blogful-test";' -U postgres
    - psql -c 'CREATE USER ubuntu;' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ubuntu;' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ubuntu;' -U postgres
    - createdb ubuntu

script:
    - nosetests tests